/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import server.Server;
import session.Session;
import thread.ThreadClient;

/**
 *
 * @author Rastko
 */
public class FrameContorl extends javax.swing.JFrame {

    private Server server;
    /**
     * Creates new form FrameContorl
     */
    public FrameContorl() {
        initComponents();
        server=Session.getServer();
        tblUsers.setModel(server.getThreadServer().getTableModelUser());
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        btnUgasiServer.setEnabled(true);
        btnPokreniServer.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        brnIzbaciKorisnika = new javax.swing.JButton();
        btnUgasiServer = new javax.swing.JButton();
        btnIzbaciSveKorisnike = new javax.swing.JButton();
        btnPokreniServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsers);

        brnIzbaciKorisnika.setText("Izbaci korisnika");
        brnIzbaciKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnIzbaciKorisnikaActionPerformed(evt);
            }
        });

        btnUgasiServer.setText("Ugasi server");
        btnUgasiServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUgasiServerActionPerformed(evt);
            }
        });

        btnIzbaciSveKorisnike.setText("Izbaci sve korisnike");
        btnIzbaciSveKorisnike.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbaciSveKorisnikeActionPerformed(evt);
            }
        });

        btnPokreniServer.setText("Pokreni server");
        btnPokreniServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPokreniServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnUgasiServer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPokreniServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzbaciSveKorisnike)
                        .addGap(18, 18, 18)
                        .addComponent(brnIzbaciKorisnika))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brnIzbaciKorisnika)
                    .addComponent(btnUgasiServer)
                    .addComponent(btnIzbaciSveKorisnike)
                    .addComponent(btnPokreniServer)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnIzbaciKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnIzbaciKorisnikaActionPerformed
        int i=tblUsers.getSelectedRow();
        if(i>-1){
            ThreadClient thc=((TableModelUser)tblUsers.getModel()).getSelectedClient(i);
            server.getThreadServer().cancelCommunication(thc);
            ((TableModelUser)tblUsers.getModel()).refresh();
        }
        else
            JOptionPane.showMessageDialog(rootPane, "Niste izabrali korisnika za izbacivanje");
    }//GEN-LAST:event_brnIzbaciKorisnikaActionPerformed

    private void btnUgasiServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUgasiServerActionPerformed

        if(server.getClients().size()==0){
            server.stopServer();
            JOptionPane.showMessageDialog(rootPane, "Server je ugasen");
            btnPokreniServer.setEnabled(true);
            btnUgasiServer.setEnabled(false);
        }else{
            int k=JOptionPane.showConfirmDialog(rootPane, "Na server ima povezanih klijenata da li zelite da ih sve diskonektujete da bi ugasili server");
            if(k==JOptionPane.YES_OPTION){
                server.stopServer();
                JOptionPane.showMessageDialog(rootPane, "Server je ugasen");
                btnPokreniServer.setEnabled(true); 
                btnUgasiServer.setEnabled(false);
            }
        }
        
    }//GEN-LAST:event_btnUgasiServerActionPerformed

    private void btnIzbaciSveKorisnikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbaciSveKorisnikeActionPerformed
        if(server.getThreadServer().getUsers().size()>=1){
            server.getThreadServer().emptyAllUsers();
            ((TableModelUser)tblUsers.getModel()).refresh();
        }
    }//GEN-LAST:event_btnIzbaciSveKorisnikeActionPerformed

    private void btnPokreniServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPokreniServerActionPerformed
        try {
            server.start(Session.getPort());
            tblUsers.setModel(server.getThreadServer().getTableModelUser());
            btnPokreniServer.setEnabled(false);
            btnUgasiServer.setEnabled(true);
            JOptionPane.showMessageDialog(rootPane, "Server pokrenut!");
        } catch (IOException ex) {
            new FormServer().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnPokreniServerActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnIzbaciKorisnika;
    private javax.swing.JButton btnIzbaciSveKorisnike;
    private javax.swing.JButton btnPokreniServer;
    private javax.swing.JButton btnUgasiServer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsers;
    // End of variables declaration//GEN-END:variables
}
