/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.klijent;

import controler.Controller;
import domain.Klijent;
import form.FormMode;
import static form.FormMode.Create;
import static form.FormMode.Delete;
import static form.FormMode.Edit;
import static form.FormMode.View;
import java.io.IOException;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sesion.Session;
import thread.MojInterfejs;
import thread.ThreadClock;

/**
 *
 * @author Rastko
 */

public class FormKlijent extends javax.swing.JDialog implements MojInterfejs{

    /**
     * Creates new form FormKlijent
     */
    Klijent klijentSaForme;
    private Thread thc;
    public FormKlijent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            setLocationRelativeTo(null);
            lblKorisnik.setText("Trenutni korisnik:" + Session.getCurrentUser().getFirstName() + " " + Session.getCurrentUser().getLastName());
            thc=new ThreadClock(txtClock);
            thc.start();
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            Session.getInstance().getThread().setMojInterfejs(this);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    public FormKlijent(java.awt.Frame parent, boolean modal, FormMode mode) {
        this(parent, modal);
        changeMode(mode);
    }

    public FormKlijent(java.awt.Frame parent, boolean modal, Klijent klijent) {
        this(parent, modal, FormMode.View);
        klijentSaForme = klijent;
        populateKlijent();
    }

        public void endProgram(){
        JOptionPane.showMessageDialog(rootPane, "Server vam je prekinuo konekciju");
        this.dispose();      
        System.exit(0);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblKorisnik = new javax.swing.JLabel();
        txtClock = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblIme = new javax.swing.JLabel();
        lblPrezime = new javax.swing.JLabel();
        lblBrojTelefona = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        txtBrojTelefona = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnIzbrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnAzuriraj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Korisnik"));

        lblKorisnik.setText("jLabel1");

        txtClock.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKorisnik)
                    .addComponent(txtClock))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblKorisnik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClock)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        lblId.setText("ID:");

        lblIme.setText("Ime:");

        lblPrezime.setText("Prezime:");

        lblBrojTelefona.setText("Broj telefona:");

        lblEmail.setText("Email:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblIme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIme))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblPrezime)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrezime))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblBrojTelefona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBrojTelefona))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIme)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrezime)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBrojTelefona)
                    .addComponent(txtBrojTelefona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnIzbrisi.setText("Izbrisi");
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAzuriraj.setText("Azuriraj");
        btnAzuriraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSacuvaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAzuriraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIzbrisi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzbrisi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnCancel)
                    .addComponent(btnAzuriraj))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        thc.interrupt();
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAzurirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajActionPerformed
        changeMode(FormMode.Edit);
    }//GEN-LAST:event_btnAzurirajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        Klijent klijent = new Klijent(Long.parseLong(txtId.getText().trim()), txtIme.getText().trim(), txtPrezime.getText().trim(), txtBrojTelefona.getText().trim(), txtEmail.getText().trim());
        if (klijent.equals(klijentSaForme)) {
            JOptionPane.showMessageDialog(this, "Niste izmenili podatke o klijentu, izmenite ih pa potom pritisnite izmeni");
        } else {
            try {
                if (Controller.getInstance().updateKlijent(klijent)) {
                    JOptionPane.showMessageDialog(this, "Uspesno izmenjen klijent");
                    klijentSaForme.setBrojTelefona(klijent.getBrojTelefona());
                    klijentSaForme.setEmail(klijent.getEmail());
                    klijentSaForme.setIme(klijent.getIme());
                    klijentSaForme.setPrezime(klijent.getPrezime());
                    populateKlijent();
                } else {
                    JOptionPane.showMessageDialog(this, "Klijent nije izmenjen");
                }
            } catch (Exception e) {
                if(e instanceof SocketException)
                    endProgram();
                JOptionPane.showMessageDialog(this, e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        String ime = txtIme.getText().trim();
        String prezime = txtPrezime.getText().trim();
        String brojTelefona = txtBrojTelefona.getText().trim();
        String email=txtEmail.getText().trim();
        Klijent klijent = new Klijent(ime, prezime, brojTelefona, email);
        if (ime.equals("") || prezime.equals("")) {
            JOptionPane.showMessageDialog(this, "Morate uneti barem ime i preime novog klijenta");
        } else {
            try {
                if (Controller.getInstance().addKlijent(klijent)) {
                    JOptionPane.showMessageDialog(this, "Klijent uspesno sacuvan");
                    txtBrojTelefona.setText("");
                    txtEmail.setText("");
                    txtIme.setText("");
                    txtPrezime.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Klijent nije sacuvan");
                }
            } catch (Exception e) {
                if(e instanceof SocketException)
                    endProgram();
                JOptionPane.showMessageDialog(this, e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
        int k = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da obrisete izabranog klijenta", "Brisanje pregleda", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (k == 0) {
            try {
                if (Controller.getInstance().deleteKlijent(klijentSaForme)) {
                    JOptionPane.showMessageDialog(this, "Klijent uspesno izbrisan");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Klijent nije izbrisan");
                }
            } catch (Exception e) {
                if(e instanceof SocketException)
                    endProgram();
                JOptionPane.showMessageDialog(this, e.getMessage());
                e.printStackTrace();
            }
        }
        if (k == 2) {
            this.dispose();
        }
    }//GEN-LAST:event_btnIzbrisiActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            Session.getInstance().getThread().setMojInterfejs(this);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzuriraj;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBrojTelefona;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIme;
    private javax.swing.JLabel lblKorisnik;
    private javax.swing.JLabel lblPrezime;
    private javax.swing.JTextField txtBrojTelefona;
    private javax.swing.JLabel txtClock;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void changeMode(FormMode mode) {
        switch (mode) {
            case View:
                txtId.setEditable(false);
                txtBrojTelefona.setEditable(false);
                txtEmail.setEditable(false);
                txtIme.setEditable(false);
                txtPrezime.setEditable(false);
                btnCancel.setVisible(true);
                btnIzbrisi.setVisible(true);
                btnIzmeni.setVisible(false);
                btnSacuvaj.setVisible(false);
                btnAzuriraj.setVisible(true);
                break;
            case Edit:
                txtId.setEditable(false);
                txtBrojTelefona.setEditable(true);
                txtEmail.setEditable(true);
                txtIme.setEditable(true);
                txtPrezime.setEditable(true);
                btnCancel.setVisible(true);
                btnIzbrisi.setVisible(false);
                btnIzmeni.setVisible(true);
                btnSacuvaj.setVisible(false);
                btnAzuriraj.setVisible(false);
                break;
            case Create:
                txtId.setEditable(false);
                txtBrojTelefona.setEditable(true);
                txtEmail.setEditable(true);
                txtIme.setEditable(true);
                txtPrezime.setEditable(true);
                btnCancel.setVisible(true);
                btnIzbrisi.setVisible(false);
                btnIzmeni.setVisible(false);
                btnSacuvaj.setVisible(true);
                btnAzuriraj.setVisible(false);
                break;
            case Delete:
                txtId.setEditable(false);
                txtBrojTelefona.setEditable(false);
                txtEmail.setEditable(false);
                txtIme.setEditable(false);
                txtPrezime.setEditable(false);
                btnCancel.setVisible(true);
                btnIzbrisi.setVisible(true);
                btnIzmeni.setVisible(false);
                btnSacuvaj.setVisible(false);
                btnAzuriraj.setVisible(false);
                break;
        }
    }

    private void populateKlijent() {
        txtId.setText(Long.toString(klijentSaForme.getKlijentId()));
        txtBrojTelefona.setText(klijentSaForme.getBrojTelefona());
        txtEmail.setText(klijentSaForme.getEmail());
        txtIme.setText(klijentSaForme.getIme());
        txtPrezime.setText(klijentSaForme.getPrezime());
    }
}
