/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;


import controler.Controller;
import form.doktor.FormDoktor;
import form.doktor.FormDoktorTable;
import form.klijent.FormKlijent;
import form.klijent.FormKlijentTable;
import form.pregled.FormPregled;
import form.pregled.FormPregledTable;
import form.termin.FormTermin;
import form.usluga.FormUsluga;
import java.io.IOException;
import java.net.SocketException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import sesion.Session;
import thread.MojInterfejs;
import thread.ThreadClock;


 
/**
 *
 * @author Rastko
 */
public class FormMain extends javax.swing.JFrame implements MojInterfejs{

    /**
     * Creates new form FormMain
     */
    private Thread thc;
    public FormMain() {
        try {
            initComponents();
            setLocationRelativeTo(null);
            jLabel1.setText("Trenutni Korisnik:"+Session.getCurrentUser().getFirstName()+" "+Session.getCurrentUser().getLastName());
            thc=new ThreadClock(txtClock);
            thc.start();
            this.setDefaultCloseOperation(EXIT_ON_CLOSE);
            Session.getInstance().getThread().setMojInterfejs(this);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtClock = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        meniPregled = new javax.swing.JMenu();
        meniPregledNovi = new javax.swing.JMenuItem();
        meniPregledPretraga = new javax.swing.JMenuItem();
        menuUsluga = new javax.swing.JMenu();
        menuItemUsluge = new javax.swing.JMenuItem();
        meniKlijent = new javax.swing.JMenu();
        meniKlijentNovi = new javax.swing.JMenuItem();
        meniKlijentPretraga = new javax.swing.JMenuItem();
        meniDoktori = new javax.swing.JMenu();
        menuItemNoviDoktor = new javax.swing.JMenuItem();
        menuItemPretragaDoktora = new javax.swing.JMenuItem();
        meniZakazivanje = new javax.swing.JMenu();
        meniItemTermini = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Korisnik"));

        jLabel1.setText("Trenutni korisnik:");

        txtClock.setForeground(new java.awt.Color(0, 204, 0));
        txtClock.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtClock))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        meniPregled.setText("Pregled");

        meniPregledNovi.setText("Novi pregled");
        meniPregledNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniPregledNoviActionPerformed(evt);
            }
        });
        meniPregled.add(meniPregledNovi);

        meniPregledPretraga.setText("Pretraga pregleda");
        meniPregledPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniPregledPretragaActionPerformed(evt);
            }
        });
        meniPregled.add(meniPregledPretraga);

        jMenuBar1.add(meniPregled);

        menuUsluga.setText("Usluga");

        menuItemUsluge.setText("Usluge");
        menuItemUsluge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUslugeActionPerformed(evt);
            }
        });
        menuUsluga.add(menuItemUsluge);

        jMenuBar1.add(menuUsluga);

        meniKlijent.setText("Klijent");

        meniKlijentNovi.setText("Novi klijent");
        meniKlijentNovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniKlijentNoviActionPerformed(evt);
            }
        });
        meniKlijent.add(meniKlijentNovi);

        meniKlijentPretraga.setText("Pretraga klijenta");
        meniKlijentPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniKlijentPretragaActionPerformed(evt);
            }
        });
        meniKlijent.add(meniKlijentPretraga);

        jMenuBar1.add(meniKlijent);

        meniDoktori.setText("Doktori");

        menuItemNoviDoktor.setText("Novi doktor");
        menuItemNoviDoktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNoviDoktorActionPerformed(evt);
            }
        });
        meniDoktori.add(menuItemNoviDoktor);

        menuItemPretragaDoktora.setText("Pretraga doktora");
        menuItemPretragaDoktora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaDoktoraActionPerformed(evt);
            }
        });
        meniDoktori.add(menuItemPretragaDoktora);

        jMenuBar1.add(meniDoktori);

        meniZakazivanje.setText("Zakazivanje");

        meniItemTermini.setText("Termini");
        meniItemTermini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniItemTerminiActionPerformed(evt);
            }
        });
        meniZakazivanje.add(meniItemTermini);

        jMenuBar1.add(meniZakazivanje);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meniPregledNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniPregledNoviActionPerformed
        JDialog formPregled=new FormPregled(this,true,FormMode.Create);
        formPregled.setVisible(true);
    }//GEN-LAST:event_meniPregledNoviActionPerformed

    private void meniPregledPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniPregledPretragaActionPerformed
        FormPregledTable fpt=new FormPregledTable(this, rootPaneCheckingEnabled);
        fpt.setVisible(true);
    }//GEN-LAST:event_meniPregledPretragaActionPerformed

    private void meniKlijentNoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniKlijentNoviActionPerformed
        FormKlijent fk= new FormKlijent(this, rootPaneCheckingEnabled,FormMode.Create);
        fk.setVisible(true);
    }//GEN-LAST:event_meniKlijentNoviActionPerformed

    private void meniKlijentPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniKlijentPretragaActionPerformed
        FormKlijentTable fkt=new FormKlijentTable(this, rootPaneCheckingEnabled);
        fkt.setVisible(true);
    }//GEN-LAST:event_meniKlijentPretragaActionPerformed

    private void meniItemTerminiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniItemTerminiActionPerformed
        new FormTermin(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_meniItemTerminiActionPerformed

    private void menuItemNoviDoktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNoviDoktorActionPerformed
       new FormDoktor(this, true, FormMode.Create).setVisible(true);
    }//GEN-LAST:event_menuItemNoviDoktorActionPerformed

    private void menuItemPretragaDoktoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretragaDoktoraActionPerformed
        new FormDoktorTable(this, true).setVisible(true);

    }//GEN-LAST:event_menuItemPretragaDoktoraActionPerformed

    private void menuItemUslugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUslugeActionPerformed
        new FormUsluga(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemUslugeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            //Controller.getInstance().logOut();
            thc.interrupt();
            this.dispose();
            new FormLogin().setVisible(true);
        } catch (Exception ex) {
            if(ex instanceof SocketException)
                endProgram();
            else
                ex.printStackTrace();

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        try {
            Session.getInstance().getThread().setMojInterfejs(this);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu meniDoktori;
    private javax.swing.JMenuItem meniItemTermini;
    private javax.swing.JMenu meniKlijent;
    private javax.swing.JMenuItem meniKlijentNovi;
    private javax.swing.JMenuItem meniKlijentPretraga;
    private javax.swing.JMenu meniPregled;
    private javax.swing.JMenuItem meniPregledNovi;
    private javax.swing.JMenuItem meniPregledPretraga;
    private javax.swing.JMenu meniZakazivanje;
    private javax.swing.JMenuItem menuItemNoviDoktor;
    private javax.swing.JMenuItem menuItemPretragaDoktora;
    private javax.swing.JMenuItem menuItemUsluge;
    private javax.swing.JMenu menuUsluga;
    private javax.swing.JLabel txtClock;
    // End of variables declaration//GEN-END:variables

    @Override
    public void endProgram() {
        JOptionPane.showMessageDialog(rootPane, "Server vam je prekinuo komunikaciju");
        this.dispose();
        System.exit(WIDTH);
    }
}
