/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form.usluga;

import controler.Controller;
import domain.Pregled;
import domain.Usluga;
import java.awt.Frame;
import java.net.SocketException;
import javax.swing.JOptionPane;
import sesion.Session;
import thread.ThreadClock;

/**
 *
 * @author Rastko
 */
public class FormUsluga extends javax.swing.JDialog {

    /**
     * Creates new form FormUsluga
     */
    private Thread tht;
    public FormUsluga(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lblTrenutniKorisnik.setText("Trenutni korisnik:" + Session.getCurrentUser().getFirstName() + " " + Session.getCurrentUser().getLastName());
        ThreadClock thc = new ThreadClock(lblClock);
        thc.start();
        lblIzabraniPregled.setText("Niste izabrali pregled");
        tblUsluga.setModel(new TableModelUsluga(this));
        txtId.setEditable(false);
        tht=new Thread((TableModelUsluga)tblUsluga.getModel());
        tht.start();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTrenutniKorisnik = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblNaziv = new javax.swing.JLabel();
        lblOpis = new javax.swing.JLabel();
        lblPregled = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpisUsluge = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsluga = new javax.swing.JTable();
        btnSacuvaj = new javax.swing.JButton();
        btnIzaberiPregled = new javax.swing.JButton();
        lblIzabraniPregled = new javax.swing.JLabel();
        btnIzbrisi = new javax.swing.JButton();
        btnPretraga = new javax.swing.JButton();
        txtPretraga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNazivUsluge = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        lblTrenutniKorisnik.setText("jLabel1");

        lblClock.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTrenutniKorisnik)
                    .addComponent(lblClock))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTrenutniKorisnik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblClock)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        lblId.setText("ID:");

        lblNaziv.setText("Naziv usluge:");

        lblOpis.setText("Opis usluge:");

        lblPregled.setText("Pregled na koji se usluga odnosi:");

        txtOpisUsluge.setColumns(20);
        txtOpisUsluge.setRows(5);
        jScrollPane1.setViewportView(txtOpisUsluge);

        tblUsluga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsluga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUslugaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsluga);

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnIzaberiPregled.setText("Izaberi pregled");
        btnIzaberiPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzaberiPregledActionPerformed(evt);
            }
        });

        lblIzabraniPregled.setText("Izabrani pregled");

        btnIzbrisi.setText("Izbrisi");
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        btnPretraga.setText("Pretraga");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        jLabel1.setText("Pretraga po imenu usluge");

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIzbrisi)
                        .addGap(36, 36, 36)
                        .addComponent(btnPretraga)
                        .addGap(18, 18, 18)
                        .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblPregled)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnIzaberiPregled)
                                        .addGap(10, 10, 10)
                                        .addComponent(lblIzabraniPregled))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblOpis, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblId)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(34, 34, 34)
                                                .addComponent(jButton1))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(lblNaziv)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtNazivUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(42, 42, 42)
                                        .addComponent(btnSacuvaj)))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv)
                    .addComponent(txtNazivUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPregled)
                    .addComponent(btnIzaberiPregled)
                    .addComponent(lblIzabraniPregled))
                .addGap(18, 18, 18)
                .addComponent(lblOpis)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIzbrisi)
                            .addComponent(btnPretraga)
                            .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnSacuvaj)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzaberiPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzaberiPregledActionPerformed
        new FormPregledTableIzbor((Frame) this.getParent(), true).setVisible(true);
    }//GEN-LAST:event_btnIzaberiPregledActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if (Session.getUslugaPregled() != null) {
            lblIzabraniPregled.setText("Izabrani pregled:" + Session.getUslugaPregled().toString());
        } else {
            lblIzabraniPregled.setText("Niste izabrali pregled");
        }
    }//GEN-LAST:event_formWindowGainedFocus

    public void endProgram(){
        JOptionPane.showMessageDialog(rootPane, "Server vam je prekinuo konekciju");
        this.dispose();      
        System.exit(0);

    }
    
    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        try {
            String nazivUsluge = txtNazivUsluge.getText().trim();
            String opisUsluge = txtOpisUsluge.getText().trim();
            Pregled pregled = Session.getUslugaPregled();
            Usluga u = new Usluga(opisUsluge, nazivUsluge, pregled);
            if (nazivUsluge.equals("") || opisUsluge.equals("") || pregled == null) {
                JOptionPane.showMessageDialog(rootPane, "Niste uneli sve podatke za unos usluge");
            } else {
                if (Controller.getInstance().addUsluga(u)) {
                    JOptionPane.showMessageDialog(rootPane, "Uspesno uneta usluga");
                    Session.setUslugaPregled(null);
                    lblIzabraniPregled.setText("Niste izabrali pregled");
                    ((TableModelUsluga)tblUsluga.getModel()).refreshTable();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Usluga nije uneta");
                }
            }
        } catch (Exception ex) {
            if(ex instanceof SocketException)
                endProgram();
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            System.out.println("Greska u unosu usluge");
            System.out.println(ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void tblUslugaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUslugaMouseClicked
        int i = tblUsluga.getSelectedRow();
        if (i > -1) {
            Usluga u = ((TableModelUsluga) tblUsluga.getModel()).getSelectedUsluga(i);
            txtId.setText(Long.toString(u.getUslugaId()));
            txtNazivUsluge.setText(u.getNazivUsluge());
            txtOpisUsluge.setText(u.getOpisUsluge());   
        }
    }//GEN-LAST:event_tblUslugaMouseClicked

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        String kriterijum = txtPretraga.getText().trim();
        if (kriterijum.equals("")) {
            ((TableModelUsluga) tblUsluga.getModel()).refreshTable();
        } else {
            try {
                ((TableModelUsluga) tblUsluga.getModel()).search(kriterijum);
            } catch (Exception ex) {
                if(ex instanceof SocketException)
                    endProgram();
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
        int i = tblUsluga.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(rootPane, "Niste izabrali uslugu za brisanje");
        } else {
            try {
                if (Controller.getInstance().deleteUsluga(((TableModelUsluga) tblUsluga.getModel()).getSelectedUsluga(i))) {
                    ((TableModelUsluga) tblUsluga.getModel()).refreshTable();
                }
            } catch (Exception ex) {
                if(ex instanceof SocketException)
                    endProgram();
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            System.out.println("Greska u brisanju usluge");
            System.out.println(ex.getMessage());
            ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnIzbrisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tht.interrupt();
        tht.yield();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberiPregled;
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIzabraniPregled;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblOpis;
    private javax.swing.JLabel lblPregled;
    private javax.swing.JLabel lblTrenutniKorisnik;
    private javax.swing.JTable tblUsluga;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNazivUsluge;
    private javax.swing.JTextArea txtOpisUsluge;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables
}
